[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/@prisma/client/*", "node_modules/.prisma/*"]
  external_node_modules = ["@prisma/client", "prisma"]

# Needed for dynamic routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# For SPAs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 