name: remu2
description: A Temu-like shopping app with admin dashboard
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_storage: ^11.2.6
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  http: ^1.1.0
  intl: ^0.18.1
  uuid: ^3.0.7
  flutter_staggered_grid_view: ^0.7.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  flutter_secure_storage: ^8.0.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700 